export enum ActionsTypes {
  GET_COCKTAIL_DETAILS = "GET_COCKTAIL_DETAILS",
  GET_COCKTAIL_DETAILS_PENDING = "GET_COCKTAIL_DETAILS_PENDING",
  GET_COCKTAIL_DETAILS_FULFILLED = "GET_COCKTAIL_DETAILS_FULFILLED",
  GET_COCKTAIL_DETAILS_REJECTED = "GET_COCKTAIL_DETAILS_REJECTED"
}

export interface GetCocktailDetailAction {
  type: string;
  payload: Promise<any>;
}
